### PR TITLE
ably-common integration

### PR DESCRIPTION
**Pull request by bladeSk**
Tests now use shared fixtures from ably-common submodule
Pagination updated to match the new spec https://github.com/ably/ably-js/issues/28#issue-67592535

### CODE REVIEW

**Comment by kouno** [comment]
It looks pretty good. A few details on variable names but I think that's it.

Since you have a commit mentioning an incompatibility for PHP < 5.6, maybe we should add it in our travis CI?

**Comment by bladeSk** [comment]
Alright, just a sec.
PHP versions > 5.3 are basically a superset of 5.3, so it should be enough to run the tests on 5.3. While it's possible to have Travis check all the versions, that would take 4 times as much time (5.3, 5.4, 5.5, 5.6).

**Comment by kouno** [comment]
Ok so let's just say 5.3 for my peace of mind ;).

**Comment by bladeSk** [comment]
@kouno So I started adding the getter for better readability and then I realized how messy the tests are (especially `TestOption` was super incomprehensible) and cleaned up all of them :)

PHP 5.3 support is troublesome. It doesn't always have openssl bundled (required for AES) and has outdated versions of curl and whatnot, so it's behaving oddly. I'll have to investigate that later.

**Comment by bladeSk** [comment]
Sigh, the tests didn't pass, because sandbox has crashed again.

**Comment by bladeSk** [comment]
Pushed the latest changes. I didn't realize this PR was still pending, so it got merged into this huge one.
See the commit messages for details, but tl;dr summary is - huge rewrite and clean up of AblyRest, introduction of types for Tokens, Options, etc,,prepared code for automatic fallback servers.

**Comment by bladeSk** [comment]
Added automatic token renewal.

**Comment by mattheworiordan** [comment]
Looking good, nice to see some progress on both auth & fallbacks.

**Comment by bladeSk** [comment]
The current logic is to try normal host and then fallback hosts (a-e). On failure, the first host that worked will be used from that point on throughout the session until there's another failure.
Exceptions get rethrown, as you suggested and a (hopefully) meaningful error message is logged.

**Comment by kouno** [comment]
This PR is a bit too big now. Shall we just merge it as it passes CI and address the feedback in a follow up PR? @mattheworiordan @bladeSk

**Comment by bladeSk** [comment]
Absolutely. I could then submit it to packagist and see if it's working properly with composer.

**Comment by mattheworiordan** [comment]
In regards to the host shuffling, reading the code it is not obvious what is going on.  I would definitely prefer that every request always tries the default host first, and then tries a random fallback host in order after.  If you want to retain the last known good fallback host at the top of that list that is fine, however the initial request should always go to `rest.ably.io` first for every request.  Therefore, please can this be refactored so that any developer reading this code can understand what happens clearly from the code.

**Comment by bladeSk** [comment]
Done. See this commit https://github.com/bladeSk/ably-php/commit/9e28e3b95b55f1ee19e81c99a525c0f1f7b92240

**Pull request merged**
