### PR TITLE
Use "http_proxy" env variable if defined to set the CURLOPT_PROXY opt…

### PR DESCRIPTION
**Pull request by DamienHarper**
…ion.

### CODE REVIEW

**Comment by funkyboy** [comment]
@DamienHarper Thanks a lot for this contribution!

This looks good to me. And the [failures in CI](https://travis-ci.org/ably/ably-php/builds/386721985) seem not related to the change.
@jdavid WDYT?

**Comment by funkyboy** [comment]
@DamienHarper We will merge [this](https://github.com/ably/ably-php/pull/53) first, then rebase this branch on master and see how tests go. Soon :)

**Comment by DamienHarper** [comment]
Done

**Comment by funkyboy** [comment]
@DamienHarper Merged. You deserve some swag :) We'll get in touch.
Thanks!

**Comment by mattheworiordan** [comment]
Thanks @DamienHarper, we appreciate the contribution. Drop us a line at support@ably.io and we'll send over something small as a thanks!

**Pull request merged**
