### PR TITLE
Use "https_proxy" env variable if defined to set the CURLOPT_PROXY option.

### PR DESCRIPTION
**Pull request by DamienHarper**

### CODE REVIEW

**Comment by funkyboy** [comment]
Looks good. Thanks.
I wonder if there’s a quick way to test when the proxy has been set @damienharper

**Comment by DamienHarper** [comment]
@funkyboy Not sure we can find a quick way to test. 
The company I work for rely on a hosting provider which blocks any trafic to the outside that do not go through its proxy. Both my previous PR and this one solve the problem in our use case, that's how I test it ;)

**Comment by funkyboy** [comment]
I think some unit test along the lines of these is enough https://github.com/ably/ably-php/blob/master/tests/TypesTest.php
Like “set proxy and check that is set”, without actually performing a request.

**Comment by DamienHarper** [comment]
@funkyboy @jdavid any chance this one gets merged and released (it's almost the same as #51 which has  already been merged and released today)?

**Comment by mattheworiordan** [comment]
@DamienHarper we had assumed no one needed this so parked it.  I assume you still need to connect through a proxy?  If so, I will see if we can get this bundled in later this week after our 1.1 release (hopefully tomorrow)

**Comment by DamienHarper** [comment]
@mattheworiordan thanks for the feedback. 
As you guess, we still are using the same hosting provider (we won't change anytime soon) so we still need to go through their proxy (for both HTTP and HTTPS protocols)
Until this PR is merged and released, the only solution for us right now is to use our own fork including the code from this PR.

**Comment by mattheworiordan** [comment]
@jdavid are you happy for us to merge this?

**Comment by mattheworiordan** [comment]
@DamienHarper this is merged and now released as 1.1.1.  Sorry this took so long!

**Comment by DamienHarper** [comment]
@mattheworiordan @funkyboy @jdavid thanks!

**Pull request merged**
