### PR TITLE
Push

### PR DESCRIPTION
**Pull request by jdavid**
Follow up from #79 

This is a feature branch, all changes have been reviewed already.

### CODE REVIEW

**Comment by jdavid** [comment]
@mattheworiordan

**Comment by mattheworiordan** [comment]
> So now which are the next steps? Should I change this PR to Ready for review?

Yes.  And @paddybyers or I can merge / approve etc.  Thanks,.

**Comment by mattheworiordan** [comment]
Merged, thanks, should we do a release @jdavid?

**Comment by mattheworiordan** [comment]
@tomczoink in case anything needs updating in the docs, looks like Push is now supported! 👍

**Comment by jdavid** [comment]
@mattheworiordan yes I think so, 1.1.2 ?

**Comment by mattheworiordan** [comment]
>  I think so, 1.1.2 ?

Sure, if that's the next patch release version.  Please confirm when done. 

Thanks 🙏

**Comment by jdavid** [comment]
done https://packagist.org/packages/ably/ably-php#1.1.2

**Comment by mattheworiordan** [comment]
Awesome, tahnks

**Pull request merged**
